---
title: "Vetiver POC"
output: html_notebook
---

```{r setup}
# Packages ----
library(vetiver)
library(tidymodels)
library(pins)
```


This document follows along with the [vetiver documentation](https://vetiver.tidymodels.org/)

```{r data}
data(Sacramento, package = "modeldata")
```

```{r model-fit}
rf_spec <- rand_forest(mode = "regression")
rf_form <- price ~ type + sqft + beds + baths

rf_fit <- workflow(rf_form, rf_spec) |> 
  fit(Sacramento)
```

Create vetiver model
```{r}
v <- vetiver_model(rf_fit, "vetiver-poc")
v
```

Pin the model to RSC
```{r}
model_board <- board_rsconnect(auth = "envvar")
# The name of the pin is the name given to `vetiver_model()`
model_board |> 
  vetiver_pin_write(v)
```

Predict against the pinned model
```{r}
pinned_model <- vetiver_pin_read(model_board, "vetiver-poc")
# Can I generate predictions against a vetiver model locally?
predict(pinned_model, Sacramento)
```

Generate Plumber skeleton
```{r}
vetiver_write_plumber(model_board, "vetiver-poc")
```




